apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: NodePort
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30100