apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: mongo-express:1.0.2-20
        ports:
        - containerPort: 8081 #using this port as per the mongo-express documentation on the docker hub
        env: 
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret #the name of the secrets file
              key: mongo-user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongo-config #the name of the config file
              key:  mongo-url